### PR TITLE
Add CPPFLAGS argument for C preprocessor directives.  Bump versions to 0.76 & avoid test/29* conflict.

### PR DESCRIPTION
**Pull request by wbraswell**
When combined with the pending Inline::Filters v0.17 code, this pull request solves Inline::C issue #42

perl11/Inline-Filters#1

This is a resubmitted pull request, to bump all version numbers to v0.76 (necessary for Inline::Filters dependency check), and to avoid test/29* file name conflict with @mohawk2's also-pending pull request.

### CODE REVIEW

**Comment by wbraswell** [comment]
@sisyphus 
Are you empowered to merge this pull request?  Inline::Filters and RPerl are both now broken, waiting for this very simple pull request to be accepted...  Thanks in advance!  :-)

**Comment by dankowitz** [comment]
Sorry I’m not empowered to make a pull request for either of those modules.
AND
Checking the Inline::C Makefile.PL for line 10 - it’s not commented out.
Still gives same error.
File attached  - thanks for hanging in on this!

On Jun 26, 2015, at 10:13 PM, sisyphus <notifications@github.com<mailto:notifications@github.com>> wrote:


@sisyphus<https://github.com/sisyphus>
Are you empowered to merge this pull request? Inline::Filters and RPerl are both now broken, waiting for this very simple pull request to be accepted... Thanks in advance! :-)

**Comment by sisyphus** [comment]
I believe I am empowered to perform the merge .... at least there's a "Merge pull request" button staring at me, just screaming out to be pressed.
But, if that's the right thing to do, then why hasn't someone else already done it ?
(That's the bit that bothers me.)

Plus I haven't paid a lot of attention to this thread, I'm old & stupid & lazy, with minimal git fu and I don't want to go stepping on someone else's toes.

Sorry if I'm therefore being obstructionist; that's certainly not a role that I want to take on.

As an interim fix can you get mileage from:
CCFLAGSEX => $Config{cppflags},

Or do you really need to be able to specify CPPFLAGS separate from CCFLAGS ?

Cheers,
Rob

**Comment by wbraswell** [comment]
@sisyphus 
CCFLAGS and CCFLAGSEX do not get passed to Inline::Filters, and Inline::Filters calls the C preprocessor, which is why we must have the new option CPPFLAGS.
The only reason I can tell that this and the other pending pull request have not been merged is simply that @ingydotnet is missing or too busy to help.
Both pull requests seem good and should be merged immediately, please help, thanks!

**Comment by wbraswell** [comment]
@sisyphus 
Thanks so much for merging this pull request!
Are you also empowered to release v0.76 onto CPAN so we can actually get up and running?

**Comment by sisyphus** [comment]
Can't you just upload your own "unofficial release" of Inline-C-0.76 to CPAN.
I recall Reini Urban uploading unofficial releases of Inline::C to CPAN in the past - for similar reasons to yours.

I don't know whether I'm empowered to make an official release of Inline::C, but I certainly don't know the process for making one.
I think it's some arcane procedure involving Dist::Zilla ... I really don't know, and I'm not about to try.

Has Ed gone missing, too ?

Cheers,
Rob

**Comment by wbraswell** [comment]
I also do not know the procedure to release v0.76 to CPAN, and I do not wish to create unofficial releases if at all possible.
I guess we really just need @ingydotnet

**Comment by sisyphus** [comment]
The correct term for what I was thinking of is "Unauthorized Release". Basically, anyone can make one by simply uploading a source distro to CPAN.
I could do an Inline-C-0.76 that shows up at http://search.cpan.org/~sisyphus/ (and could be downloaded from there).
Only thing is, I don't think the cpan command will find it automatically - so the 'cpan -i Inline::C' command would still  install 0.75.
But the module would be available for download from my CPAN home directory, and I think that a "fully-qualified-type" cpan command that would install my unauthorized release does exist.
(But I don't know for sure if that's correct, and I don't know what that command is.)

If you think that might be useful to you, let me know, and I'll upload that unauthorized Inline-C-0.76 tomorrow. (Hell, FAIK it might turn out to be an __official__ release .... which might make things interesting. I'm assuming that I can't do any long lasting damage that couldn't be fixed by simply deleting my Inline-C-0.76 release from CPAN.)

**Comment by dankowitz** [comment]
?If you put the 0.76 version on your site, I will certainly try it!

Thank you - a.

________________________________

**Comment by wbraswell** [comment]
@sisyphus 
I do not wish to have any unauthorized releases on CPAN, I've done it before and it is a pain and also it is less-than-legitimate.
SO THEREFORE how can we check in advance to see if you have the proper permissions to release an OFFICIAL version of Inline::C v0.76 on CPAN?
Thanks!
~ Will

**Pull request merged**
