### PR TITLE
Add test, and Cookbook example, of array-ref arg

### PR DESCRIPTION
**Pull request by mohawk2**
Gives budding Inline users code they can cut+paste for instant working code.

### CODE REVIEW

**Comment by zmughal** [comment]
:+1: Nice!

**Comment by sisyphus** [comment]
From: mohawk2
Sent: Sunday, March 22, 2015 2:50 PM
To: ingydotnet/inline-c-pm
Subject: [inline-c-pm] Add test, and Cookbook example, of array-ref arg 
(#39)

Ed,

> Gives budding Inline users code they can cut+paste for instant working 
> code.

Why the call to "SvGETMAGIC(array);" ?
The test script seems to work just as well without it.

Also, on perl-5.16 (and presumably earlier), the build fails with:

_29refargs_t_f0c98d.o:_29_t_f0c98d.c:(.text+0x34): undefined reference to 
`_av_top_index'

We can remedy this with (eg):

#ifndef av_top_index
#define av_top_index AvFILL
#endif

Cheers,
Rob

**Comment by mohawk2** [comment]
@sisyphus I zapped the `SvGETMAGIC` stuff since as you said, it was unnecessary. There now isn't any reference to `av_top_index` so I haven't added the `#define` you mention.

@ingydotnet Feel like merging this? I rebased it against current `master`.

**Comment by mohawk2** [comment]
@perlpunk Time for merge maybe?

**Comment by perlpunk** [comment]
Thanks, merged!

**Pull request merged**
