### PR TITLE
Fix Include Dir Behavior, Replace -I With -iquote

### PR DESCRIPTION
**Pull request by wbraswell**
Fix for bug
https://github.com/ingydotnet/inline-c-pm/issues/72

### CODE REVIEW

**Comment by mohawk2** [comment]
Am I right that `-iquote` is a GCC-only flag, and therefore will break `Inline::C` for anyone not using GCC?

**Comment by wbraswell** [comment]
@mohawk2 
no, you are not correct
https://github.com/ingydotnet/inline-c-pm/issues/72#issuecomment-451359214

**Comment by mohawk2** [comment]
So I have just seen. That justification should be put here. I do not think breaking `Inline::C` on even one known compiler is justified by the problem you've just discovered.

**Comment by wbraswell** [comment]
@mohawk2 
We are not breaking Inline::C on any compilers.  Please try to keep up with the conversation, and leave your negativity at the door, thanks!
https://github.com/ingydotnet/inline-c-pm/issues/72#issuecomment-451514532

**Comment by wbraswell** [comment]
replaced by new MS-friendly pull request
https://github.com/ingydotnet/inline-c-pm/pull/74

**Comment by sisyphus** [comment]
William,

I'll merge the pull request (#74) tomorrow if no-one has requested any
modifications to it.
I wonder if we might discover other cases where '-iquote' is not being
handled correctly.
If no-one volunteers information about the existence of these "other
cases", then I can think of only one way to find out ;-)

Cheers,
Rob

**Pull request closed without merging**
