### PR TITLE
Fix Include Dir Behavior: Remove Test-For-Errors, Avoid Microsoft Errors

### PR DESCRIPTION
**Pull request by wbraswell**
FULL COMMIT MESSAGE: 
Remove Test-For-Errors For Simplicity, Replace Fake stdio.h With iquote_test.h & Require Inline v0.81 To Avoid Microsoft Errors

Remove test-for-errors as discussed here:
https://github.com/ingydotnet/inline-c-pm/pull/80#issuecomment-457880343

Use iquote_test.h instead of stdio.h, as discussed here:
https://github.com/ingydotnet/inline-c-pm/issues/72#issuecomment-461026410

Upgrade to Inline v0.81 as discussed here:
https://github.com/ingydotnet/inline-c-pm/issues/72#issuecomment-460187963

### CODE REVIEW

**Comment by wbraswell** [comment]
@sisyphus 
I followed your new testing methodology.  Can you please review and merge this pull request?

**Comment by sisyphus** [comment]
I'll be able to review and commit after I've returned home (Tuesday March
5).
Won't be able to do anything prior to that.

Cheers,
Rob

**Comment by wbraswell** [comment]
@sisyphus 
Okay thanks, talk to you then!  :-)

**Comment by sisyphus** [comment]
Ok - is there an easy way that I can make the changes to my local copy of
the Inline::C repo without actually merging the pull request ?
It seems a bit arse-about to be merging pull requests to master without
first seeing what the end result will be ... though I'm quite happy to do
just that, and make any necessary amendments later (if that's what it
takes).

Cheers,
Rob

**Comment by mohawk2** [comment]
Yes, there is - see the "view command line instructions" link next to the "Merge" button.

Alternatively, you can:

```
git remote add braswell git@github.com:wbraswell/inline-c-pm.git
git fetch --all
git checkout braswell/master
# now things are on your disk same as on his master branch
```

**Comment by sisyphus** [comment]
Thanks.
I merged the pull request, then pushed a new version of
test/31include_dirs_angle_brackets.t.
That file now uses Test::More and makes the test a TODO for MS compilers.
In that file I also replaced:

INC => "-I$cwd/test/test_header/";
with
INC => "-I$cwd/t/test_header/";

I *think* that's right.

Another set of eyes on this would be re-assuring. I haven't created a new
distro to check that everything is generated correctly, which leaves me
feeling a bit nervous.
I did run tests on the new test/31include_dirs_angle_brackets.t and found
it to behave as we want.

Kudos to Will, for all the work he did.

Cheers,
Rob

**Comment by sisyphus** [comment]
Ummm .... I've just had an idea for a fix for MS compilers.
With those compilers it might work if, instead of setting
$o->{ILSM}{MAKEFILE}{INC} to "-I\"$FindBin::Bin\"", we append $FindBin::Bin
to $ENV{INCLUDE}.

Tina, it might be worth holding off on making another devel release while I
check that out.

Cheers,
Rob

**Comment by sisyphus** [comment]
All works well if, for MS compilers, I replace:

$o->{ILSM}{MAKEFILE}{INC} = "-I\"$FindBin::Bin\"";
with
$ENV{INCLUDE} .= ";$FindBin::Bin";
in C.pm's validate() sub.

(And I remove the warning and comment about MS compiler's lack of iquote.)

The TODO block can then be removed from the test 31 script, and all test
scripts pass. (I also had to alter  tests 1 and 5 in
t/23validate.t because they detect the changed behaviour - but that's of no
concern.)

However, with MS compilers only, there can still be a small DWIM
cost brought about by this change to C.pm.
Obviously, if someone's C code specifies:

#include "some_header,h"

then the intention is to include the "some_header.h" that's in the same
directory as the script.

If there's no "-I" switch pointing to the  location of the intended
"some_header.h" then the file that gets included will be the
first "some_header.h" found in the $ENV{INCLUDE} search path - which may
not necessarily be the intended one.
I could solve that by prepending (instead of appending) $FindBin::Bin to
$ENV{INCLUDE} but that just reintroduces the original problem that William
struck ;-)

My vote would be for me to commit these latest changes.
I don't even know if anyone is using perl built with an MS compilers, let
alone building Inline::C with one.
Even if someone is, the chance of them loading an unintended header file in
the way I've just outlined, would be fairly remote.

The alternative is to just go with git as it stands at the moment.

What do others think ?

Cheers,
Rob

**Comment by wbraswell** [comment]
@sisyphus 
I vote for accepting your new changes, with the caveat that we should still be emitting a warning on MS systems with information about the remote-but-not-impossible loading-of-unintended-header-file issue.

**Comment by sisyphus** [comment]
Ok - how about (in C.pm) :

if (($Config{osname} eq 'MSWin32') and ($Config{cc} =~ /\b(?:cl|icl)/)) {
  warn "\n   Any header files specified relative to\n",
       "   $FindBin::Bin\n",
       "   will be included only if no file of the same relative path
and\n",
       "   name is found elsewhere in the search locations (including
those\n",
       "   specified in \$ENV{INCLUDE}).\n",
       "   Otherwise, that header file \"found elswhere\" will be
included.\n";
  warn "  ";    # provide filename and line number.
  $ENV{INCLUDE} .= ";$FindBin::Bin";
}

Re-phrasing suggestions welcome.

The warning appears well formatted, but it does make the running of the
test suite rather noisy.
At least the name of the file (and the line number) from which the warning
emanates is visible - for any user to remove if such is the preference.
Also, it's worth pointing out that the warning appears only when the C code
is to be compiled.

And I've created (local only, at present time) a test file that
demonstrates the failure as a TODO. The same test file also demonstrates
that gcc is not subject to the same issue.

Cheers,
Rob

**Comment by rongrw** [comment]
@sisyphus , thank you for putting so much effort into this issue.

My personal preference would be to keep things in the current master as they are. I find storing parameter values in the environment block rather vulnerable. Storing values in $o->{ILSM} is much more private and consistent with the way validate() handles input parameters.

It does appear that amongst so many C compilers, the MS compiler is the only one that doesn't provide the "-iquote" feature. As such I feel that more than sufficient effort has already been invested to accomodate the MS compiler. And who knows, Microsoft may even decide to implement the "-iquote" feature in the future to align more closely with the GCC compilers.

**Comment by sisyphus** [comment]
Admittedly I don't have a good understanding of security concerns, but note
that this whole scenario of setting $o->{ILSM}{MAKEFILE}{INC} to
"-I\"$FindBin::Bin\"" (or of appending $FindBin::Bin to the end
of $ENV{INCLUDE} ) is avoided if $o->UNTAINT is false.
I'm guessing (untested & uninformed) that $o->UNTAINT  is false when the
script is run in Taint mode, and that might perhaps  be the way to address
the concern that you express ... dunno.

In any case I have no personal preference about the way this issue is
treated as I don't do the things that could make me a victim of it - though
it would take only a momentary lapse of reason to render the latter part
of that statement untrue ;-)

For mine, the first mistake was to include this "-I\"$FindBin::Bin\"" stuff
in the first place.
That it was not immediately knocked on the head was the second mistake.
It would be nice to now finally bludgeon it to death, but that would
probably be a third mistake  - as someone would be bound to notice, and
complain ;-)

Thank you for your input.

Cheers,
Rob

**Comment by wbraswell** [comment]
@sisyphus 
Yes your proposed warning message and wording seems perfectly adequate, I vote we move ahead.

@rongrw 
While I am unqualified to comment on the security concerns of `$o->{ILSM}`, I feel that the easiest and safest path forward at this juncture is to accept Rob's current proposed MS warning message, and hopefully lay this issue to rest until such a time as MS may upgrade their compilers (which may be years or never).

**Comment by rongrw** [comment]
Can I confirm that the proposed line of code,

    $ENV{INCLUDE} .= ";$FindBin::Bin";

would only be executed by the MS compiler?

**Comment by wbraswell** [comment]
@rongrw 
I believe that is correct, yes.  Although we should have final confirmation from @sisyphus

**Comment by sisyphus** [comment]
Yes, it's only MS compilers that are affected.

In Inline-C-0.79_002, C.pm contained:

    if (not $o->UNTAINT) {
        require FindBin;
        if (not defined $o->{ILSM}{MAKEFILE}{INC}) {
            # detect Microsoft Windows OS, and either Microsoft Visual
Studio compiler "clarm.exe" or Intel C compiler "icl.exe"
            if (($Config{osname} eq 'MSWin32') and ($Config{cc} =~
/\b(cl\b|icl)/)) {
                $o->{ILSM}{MAKEFILE}{INC} = "-I\"$FindBin::Bin\"";      #
angle-bracket includes WILL incorrectly search -I dirs
                warn q{WARNING: Microsoft compiler detected, unable to
utilize '-iquote' compiler option, falling back to '-I' which may produce
incorrect results or errors for files included in angle brackets, such as
compiling '#include <stdio.h>' when a user-defined file 'stdio.h' exists in
the calling script's directory and is wrongly located via '-I' instead of
locating the standard library file of the same name}, "\n";
            }

With my proposed changes, in Inline-C-0.79_003 that would become:

    if (not $o->UNTAINT) {
        require FindBin;
        if (not defined $o->{ILSM}{MAKEFILE}{INC}) {
            # detect Microsoft Windows OS, and either Microsoft Visual
Studio compiler "cl.exe" or Intel C compiler "icl.exe"
            if (($Config{osname} eq 'MSWin32') and ($Config{cc} =~
/\b(?:cl|icl)/)) {
                warn "\n   Any header files specified relative to\n",
                     "   $FindBin::Bin\n",
                     "   will be included only if no file of the same
relative path and\n",
                     "   name is found elsewhere in the search locations
(including those\n",
                     "   specified in \$ENV{INCLUDE}).\n",
                     "   Otherwise, that header file \"found elswhere\"
will be included.\n";
                warn "  ";    # provide filename and line number.
                $ENV{INCLUDE} .= ";$FindBin::Bin";
            }

So it will affect only known MS (or known MS-based) compilers.

I've also just now altered the comment (4th line) in the above blocks
that mentions "clarm.exe"  - whereas the MS compiler is "cl.exe".
That is, I've also changed that occurrence of "clarm.exe" to "cl.exe".

But then I noticed that the regex $Config{cc} =~ /\b(?:cl|icl)/ also
matches 'clarm'. Now, I don't know if there are any Windows perls for which
$Config{cc}  is 'clarm', but if there is then we certainly want the regex
to NOT match it.
I've therefore also changed the regex to  /\b(cl\b|icl)/ which
still matches 'cl', 'cl.exe', 'icl' and 'icl.exe' but, unlike its
predecessor, does not match 'clarm' and 'clarm.exe'.

(My understanding is that the "?:" in the original regex has some bearing
on what gets captured, but no bearing on what gets matched - so I've also
removed that "?:".)

Other than that, it's just an alteration to 23validate.t to cater for the
change in behaviour of perls that use an MS compiler -  and I'm adding
a test script to verify:
 a) that the warning being emitted by validate() is a valid one;
 b) that non-Microsoft compilers are unaffected.

Cheers,
Rob

I'll run some final testing and, all being well, will commit them to git
tonight or tomorrow morning.

**Comment by sisyphus** [comment]
I think you're right about 'clarm'. I was getting confused (brainfart) with
'clang', which is not MS.
However, with 'clang', $Config{cc} will always be 'gcc' anyway, won't it ?
That being so, we don't have to worry about matching 'clang'.

I'll change the regex to /\b(cl|icl)/

Thanks for picking up on that.

Cheers,
Rob

**Comment by wbraswell** [comment]
@sisyphus 
Yes, I believe at least _some_ clang-built Perls report "gcc" via `$Config{cc}`...
However, I'm not sure if _all_ clang-built Perls will report "gcc"?

**Comment by sisyphus** [comment]
I guess we could be more explicit and have the regex as /\b(cl\b|clarm|icl)/

That should cover all of the ones we want to include. (AFAIK, there's
only three - 'cl', 'clarm' and 'icl'. For my testing I have only cl.exe.)

Cheers,
Rob

**Comment by rongrw** [comment]
@sisyphus @wbraswell , I really like the newly proposed changes to validate() - thank you. There's just a small typo in the last sentence of your warning:

`"   Otherwise, that header file \"found elswhere\" will be included.\n";`

**elswhere** should be **elsewhere**

**Comment by sisyphus** [comment]
Ok - I've tested and pushed my revisions to git. Files affected:

lib/Inline/C.pm - as discussed.
test/test_header.h - insert comment
test/test_header/test_header.h - new file
test/23validate.t - rewrite 2 tests
test/33intended_double_quotes.t - new file

I've shied away from doing test/33intended_double_quotes.t as a normal TODO
for MS compilers.
If, with MS compilers, the correct header were to be loaded, then the
hardcoded warning in C.pm's validate() is wrong - so I'm marking that
scenario as a failure, to draw attention to the fact that the Inline::C
source is in need of alteration.
Maybe there's a better way - feel free to alter. (No offence will be taken,
nor annoyance felt.)

With the inclusion of a couple of new files, the MANIFEST will need to
change. I assume that happens automatically.

Cheers,
Rob

**Comment by wbraswell** [comment]
@sisyphus 
It looks like Travis is failing with your latest commit?
https://travis-ci.org/ingydotnet/inline-c-pm/builds/505531191

**Comment by mohawk2** [comment]
> the `MANIFEST` will need to change. I assume that happens automatically.

Yes.

The failing test is `test/31include_dirs_angle_brackets.t`.

**Comment by sisyphus** [comment]
Looking at the failure at:
https://travis-ci.org/ingydotnet/inline-c-pm/jobs/505531192

When the test/31include_dirs_angle_brackets.t test is being run, I see:
cc -c -iquote"/home/travis/build/ingydotnet/inline-c-pm/test"
-I/home/travis/build/ingydotnet/inline-c-pm/t/test_header/

It's the "-I" switch that should be locating iquote_test.h, but it
specifies the "t/test_header" directory which doesn't exist.
If I alter the test script to specify "test/test_header", then
iquote_test.h will be found as expected.

Will that be auto-corrected back to "t/test_header" when the next cpan
release is generated ?
I assumed not ... which is the only reason that I changed it in the first
place.

I meant to update that test script anyway, as it still contains the TODO
for MS compilers that is now irrelevant.
I'll update it when someone confirms  if 31include_dirs_angle_brackets.t
should specify:

INC => "-I$cwd/t/test_header/";
or whether it should specify:
INC => "-I$cwd/test/test_header/";

Cheers,
Rob

**Comment by wbraswell** [comment]
I have no idea how or why there is a renaming which happens from "test/" to "t/", this seems like a really bad idea which will cause inconsistent results between development versions and CPAN releases...

**Comment by wbraswell** [comment]
@perlpunk 
Can you please give us guidance on the "test/" vs "t/" issue?

**Comment by sisyphus** [comment]
One solution would be to simply move the "test_header" folder out of the
"test" directory.
We could, say, place "test_header" next to "test".

That way the "INC" directive becomes:
INC => "-I$cwd/test_header/";

which would be right for travis && right for cpan.

I'm assuming that "test_header" won't be renamed to "t_header" when the
cpan distro is generated. (Might be safer to instead call it something that
doesn't contain the string "test".)

I'm not all that excited by the prospect of having 2 directories for
testing purposes .... wait and see what ingy thinks.

Cheers,
Rob

**Comment by mohawk2** [comment]
This `t` vs `test` thing is why @ingydotnet uses, eg in https://github.com/ingydotnet/inline-c-pm/blob/master/test/28autowrap.t, `FindBin`. This will work whether it's on your local machine / Travis (when it's called `test`) or on CPAN (when it's called `t`).

Please ensure all test files and Inline::C libraries that add directories, such as a `-I`, quote the directory, e.g.:

`qq{-I"$directory"}`

so that the library, and tests, will work when Perl is in a "place with a space" (a directory with a space in its name, as is idiomatic on Windows).

**Comment by perlpunk** [comment]
The `test` vs. `t` thing comes from Zilla:Dist.
The idea was, I believe, that a `test` directory is more common, and only perl modules use `t`.
When creating a tarball from git, the directory is renamed to `t`.

I added FindBin two years ago to all tests:
https://github.com/ingydotnet/inline-c-pm/commit/c67607145addcffef33c733eac3918b10df1efeb
FindBin should abstract most of the test/t weirdness away.

Still, for developing Zilla::Dist distributions, it makes things much easier to install Zilla::Dist.

**Comment by sisyphus** [comment]
Right - that looks better than anything I was smart enough to work out.

So ... instead of

INC => "-I$cwd/test/test_header/";
or
INC => "-I$cwd/t/test_header/";
we would write:
INC => "-I$FindBin::Bin/test_header/";

However, because we also have to work around the "spaces in filenames and
dirnames is acceptable" idiocy (which also exists in places other than
Windows, btw), that actually needs to be:

INC => "-I\"$FindBin::Bin/test_header/\"";
or some equivalent thereto.
Right ?

I'll address that over the weekend if I don't get to it tomorrow.

I believe the only files I need to check are :

C.pm
31include_dirs_angle_brackets.t
32include_dirs_double_quotes.t
33intended_double_quotes.t

Please let me know if I've missed something.

Cheers,
Rob

**Comment by rongrw** [comment]
@sisyphus couldn't we use the syntax suggested by @mohawk2 ?

    INC => qq{-I"$FindBin::Bin/test_header"}

which I find a bit more readable.

**Comment by mohawk2** [comment]
@sisyphus It's not idiocy. It's a valid filesystem character. We should all be grateful MS didn't see fit to put any double-quotes (another valid character).

@tinita I hadn't checked to see who changed it, very nice work. Last time I looked in these tests it still used the `-d 'test'` idiom.

**Comment by sisyphus** [comment]
Just to be clear , I did not say that Inline::C is doing anything idiotic .
But allowing the character that separates command line arguments (ie the
space) to be a valid filesystem character *is* idiotic.
It's completely unnecessary and only causes complication.
And we shouldn't pick solely on Microsoft - my Ubuntu-18.04 also regards it
as valid:

$ mkdir "some place"
$ cd "some place"
$ echo $PWD
/home/sisyphus/pscrpt/t/some place

Availing myself of the option to include spaces in filenames and dirnames
is something that I steadfastly avoid - on both my Windows and Linux
machines.

**Comment by sisyphus** [comment]
The following files have just been updated in the git repo:

lib/Inline/C.pm
test/31include_dirs_angle_brackets.t
test/32include_dirs_double_quotes.t
test/33intended_double_quotes.t

They tested fine for me with both msvc-7.0 and gcc-8.1.0, even when
$FindBin::Bin contains whitespace.

Cheers,
Rob

**Comment by wbraswell** [comment]
@sisyphus :+1: 
Okay great, it looks like the Travis tests are now passing with your latest commit, I vote we move ahead with a CPAN release!

**Comment by perlpunk** [comment]
Are we ok for a dev release?

**Comment by perlpunk** [comment]
I released Inline::C 0.79_003, but still Win32::Mutex failures, see https://github.com/ingydotnet/inline-pm/pull/69

**Comment by wbraswell** [comment]
@perlpunk 
Thanks for your ongoing commitment to solve these numerous interconnected issues!  :-)
I'll wait for the Win32::Mutex failures to be fixed, then I will test it out again on my Linux system.

**Pull request merged**
