### PR TITLE
Add new recipe to the C-Cookbook

### PR DESCRIPTION
**Pull request by rongrw**
Updated the C-Cookbook (Cookbook.swim) by adding a new recipe titled "Direct Access to Perl variables". I've placed this recipe at the end of the section "Meat & Potatoes".

Also created a new file called "CONTRIBUTING".

### CODE REVIEW

**Comment by wbraswell** [comment]
@ingydotnet @sisyphus 
This pull request affects documentation only, and the contents seems to have been well-thought-out.
I suggest merging.

**Comment by ingydotnet** [comment]
I don't understand. Why are you putting `doc/Inline/C/Cookbook.pm` into `./Cookbook.swim`. The `CONTRIBUTING` file is a generated file for CPAN. It doesn't belong in the repo.

Please read and comprehend the `About` file and try again.

**Comment by wbraswell** [comment]
@ingydotnet 
The content was put into a `.swim` file based on the recommendations of @mohawk2 and @daoswald here:
https://github.com/ingydotnet/inline-c-pm/issues/56

The `CONTRIBUTING` file was also a recommendation by @daoswald ; while `CONTRIBUTING` may be automatically created by dzilla, this is not the case with the EU::MM projects I've worked on, and even GitHub's own docs talk about manually created this file:
https://help.github.com/articles/setting-guidelines-for-repository-contributors/#adding-a-contributing-file

We've all been trying our best to help @rongrw do the right thing, but since it does not meet with your approval, then it seems like you should provide some official guidance for @rongrw by clearly stating where do you want him to put the new content???

**Comment by rongrw** [comment]
Hi @ingydotnet , @wbraswell ,
Yes, I didn't place the Cookbook.swim into the correct directory. This was certainly not intentional and I do apologise for that. Unfortunately I'm still in the process of learning the github web interface.

I would like to see the new recipe make its way into the C-Cookbook because I find this doc to be such an excellent learning tool with really interesting examples. To that end, if I could be given some further advice to get the changes approved, I'll do that.

Thank you for guiding me thus far, and I do realise that you are all very busy.

**Comment by ingydotnet** [comment]
@rongrw, your contribution looks fine, but why on earth would you copy
`./doc/Inline/C/Cookbook.swim` to `./Cookbook.swim`?

I don't have a CONTRIBUTING file in any of my repos, and I'm not going to add
one here. There's a CONTRIBUTING file in the CPAN dist.

Please change `doc/Inline/C/Cookbook.swim` in place and get rid of the
CONTRIBUTING file.

**Comment by ingydotnet** [comment]
I fixed/applied your PR myself. Thanks.

**Comment by perlpunk** [comment]
I'd vote for a CONTRIBUTING file in the repo too, because people are working with the repo and not the CPAN dist, when they want to contribute. Also, github has support for it.

**Pull request closed without merging**
