### PR TITLE
support perl 5.8.1 since Pegex does again

### PR DESCRIPTION
**Pull request by mohawk2**

### CODE REVIEW

**Comment by mohawk2** [comment]
@ingydotnet @perlpunk Are you Ok with me merging and releasing this? It seems the ultimate low-risk thing.

**Comment by mohawk2** [comment]
@perlpunk ...?

**Comment by perlpunk** [comment]
I agree but I can't decide who may release.
One problem I see is that things have been pushed to master, so we would release that too.
An alternative would be to release this from an extra branch (which is possible with zild but requires one extra step - add the release date manually)

**Comment by perlpunk** [comment]
thanks, merged!

**Pull request merged**
